application:
  animal:
    cat:
      names:
        - barsik
        - persik
    dog:
      names:
        - barsik
        - persik
    shark:
      names:
        - barsik
        - persik
    wolf:
      names:
        - barsik
        - persik
