animal:
  catNames:
    - Barsik23
    - Persik34
    - Barsik45
    - Persik56
  dogNames:
    - Alleb
    - Xam
    - Anul
    - Xer
    - Ysiad
  sharkNames:
    - 123
    - 234
    - 345
    - 456
    - 567
  wolfNames:
    - AAA
    - BBB
    - CCC