application:
  animal:
    cat:
      names:
        - Barsik
        - Persik
        - Barsik1
        - Persik1
    dog:
      names:
        - Bella
        - Max
        - Luna
        - Rex
        - Daisy
    shark:
      names:
        - Orca
        - Hammerhead
        - Tiger
        - Great White
        - Silvertip
    wolf:
      names:
        - Fenrir
        - Blaze
        - Hati
        - Balto
        - Dakota